---
title: "test spdep"
output:
  html_document:
    toc: true
    toc_float: 
      collapsed: false
    number_sections: true
    fig_width: 7
    fig_height: 6
    df_print: paged
    keep_md: true
    self_contained: true
    fig_caption: true
date: "`r format(Sys.time(), '%d %B, %Y')`"
fontsize: 10pt
geometry: margin=1in
---

```{r style1, echo=FALSE, results='hide', message=FALSE, cache=FALSE}
library(knitr)
# set global chunk options
knitr::opts_chunk$set(
  fig.width=7, fig.height=7, 
  fig.path='figure/',
  fig.align='center',
  out.width='90%',
  #size="small",
  error=FALSE, prompt=TRUE, comment=NA, 
  dpi=300, dev="png", dev.args=list(pointsize=15),
  cache=TRUE, 
  cache.path="cache/",
  echo=TRUE, # set to FALSE to remove the code output
  warning=FALSE, 
  message=FALSE, cache.lazy = FALSE)

options(width=110, digits=3)
pdf.options(useDingbats = TRUE)
```

```{r setup, include=FALSE}
library(SpatialExperiment)
library(spdep)
library(ggplot2)
```

```{r}
spe <- readRDS("xenium380Cell_spe.rds")
```

```{r}
coords_df <- as.data.frame(spe@int_colData$spatialCoords)
counts_matrix <- spe@assays@data$counts
counts_df <- as.data.frame(as.matrix(spe@assays@data$counts))
```

# binning (keep empty bins)

```{r}
hex_size = 50

## 1. sf cells
## ---------------------------
coords_df$cell_id <- rownames(coords_df)

cell_sf <- sf::st_as_sf(
  coords_df,
  coords = c("x_centroid", "y_centroid"),
  crs = NA
)

## ---------------------------
## 2. Hex binning
## ---------------------------
hex_geom <- sf::st_make_grid(
  cell_sf,
  cellsize = hex_size,
  what = "polygons",
  square = FALSE
)

hex_sf <- sf::st_sf(
  hex_id = seq_along(hex_geom),
  geometry = hex_geom
)
dim(hex_sf)

cell_hex_sf <- sf::st_join(cell_sf, hex_sf, join = sf::st_intersects)
cell_hex_df <- sf::st_drop_geometry(cell_hex_sf)
dim(cell_hex_df)
length(unique(cell_hex_df$hex_id))

## ---------------------------
## 3. Aggregate counts
## ---------------------------
hex_id <- cell_hex_df$hex_id
names(hex_id) <- cell_hex_df$cell_id
hex_id <- hex_id[colnames(counts_matrix)]

n_hex <- nrow(hex_sf) # hex_sf contains ALL hexes
hex_factor <- factor(hex_id, levels = seq_len(n_hex))

H <- Matrix::sparse.model.matrix(~ hex_factor - 1)
hex_gene_counts <- counts_matrix %*% H
dim(hex_gene_counts)

hex_sf$n_cells <- as.numeric(Matrix::colSums(H))
dim(hex_sf)

ggplot()+geom_sf(data=hex_sf)+geom_sf(data=cell_hex_sf, size=0.02, aes())
```

# test local moran one LR under queen weight

## spdep

```{r}
geo <- sf::st_geometry(hex_sf)

centroids <- sf::st_centroid(hex_sf)

co.dist <- dnearneigh(centroids, 0, 1.2*50)
co.queen <- nb2listw(co.dist, style="W", zero.policy = TRUE)
wt_queen <- spdep::nb2listwdist(co.dist, centroids, type="idw", style="W", zero.policy = TRUE)
which(card(co.dist) == 0)

x <- hex_gene_counts["CXCR4",]
y <- hex_gene_counts["CXCL12",]

system.time(res_bv <- spdep::localmoran_bv(x, y, wt_queen, nsim = 9999, zero.policy = T))

p_cutoff = 0.05
hs <- hotspot(
    res_bv,
    Prname = "Pr(folded) Sim",
    cutoff = p_cutoff,
    quadrant.type = "pysal",
    p.adjust = "none"
  )

table(hs) # 1361 HH

res_bv[1:10, c("Pr(z != E(Ibvi)) Sim", "Pr(folded) Sim")]
```

## rgeoda

```{r}
library(rgeoda)

queen_w <- queen_weights(hex_sf, order=1)

get_neighbors(queen_w, idx = 1)
get_neighbors_weights(queen_w, idx = 1)

res_geo <- local_bimoran(queen_w, 
                         data.frame(receptor = x, 
                                    ligand = y),
                 permutations = 9999)

table(lisa_clusters(res_geo)) # 1369 HH

lisa_pvalues(res_geo)[1:10]
```

## scider

```{r}
colnames(hex_gene_counts) <- as.character(hex_sf$hex_id)
hex_sf <- hex_sf[match(colnames(hex_gene_counts), as.character(hex_sf$hex_id)), ]

centroids <- sf::st_centroid(hex_sf)
sp_coords <- sf::st_coordinates(centroids)
colnames(sp_coords) <- c("x_centroid", "y_centroid")
rownames(sp_coords) <- colnames(hex_gene_counts)

cd <- sf::st_drop_geometry(hex_sf)
cd <- DataFrame(cd)
rownames(cd) <- colnames(hex_gene_counts)

cd$geometry <- sf::st_geometry(hex_sf)

hex_spe <- SpatialExperiment(
  assays = list(counts = hex_gene_counts),
  colData = cd,
  spatialCoords = sp_coords
)

hex_spe

library(sciderHex)
library(scider)

hex_spe <- findNbrsSpatial(hex_spe, radius = 60, dist_func = "idw", scale = 50)
hex_spe@metadata$nbrs$cell$spatial$weight[[1]]
hex_spe@metadata$nbrs$cell$spatial$index[[1]]

sc_lisa <- sciderHex::localMoran(hex_spe, x, y, at = "cell", permutations = 9999, 
                                 cpu_threads = 1)

table(sc_lisa$cluster) # 1357 HH
```

# test local moran one LR under distance weight

## spdep

```{r}
dmax=250
dist_nb <- spdep::dnearneigh(coords, 0, dmax)
  
dist_wt <- spdep::nb2listwdist(
  dist_nb,
  hex_sf,
  type = "exp",
  style = "W",
  alpha = - log(0.01) / dmax # weight=0.01 for dist=250
)

dist_wt <- spdep::nb2listwdist(
  dist_nb,
  hex_sf,
  type = "exp",
  style = "raw",
  alpha = - log(0.01) / dmax # weight=0.01 for dist=250
)

table(dist_wt$weights[[278]])
dist_wt$neighbours[[278]]

x <- hex_gene_counts["CXCR4",]
y <- hex_gene_counts["CXCL12",]

system.time(res_bv <- spdep::localmoran_bv(x, y, dist_wt, nsim = 999, zero.policy = T))

p_cutoff = 0.05
hs <- hotspot(
    res_bv,
    Prname = "Pr(folded) Sim",
    cutoff = p_cutoff,
    quadrant.type = "pysal",
    p.adjust = "none"
  )

table(hs) # 2057 HH
```

## scider

```{r}
hex_spe <- scider::findNbrsSpatial(hex_spe, radius = 250, dist_func = "exp", standardisation = "row")

hex_spe@metadata$nbrs$cell$spatial$index[[278]]
setdiff(hex_spe@metadata$nbrs$cell$spatial$index[[278]], dist_wt$neighbours[[278]])

hex_spe <- scider::findNbrsSpatial(hex_spe, radius = 250, dist_func = "exp", standardisation = "none", scale = 250)
sc_lisa <- scider::localMoran(hex_spe, x, y, at = "cell", permutations = 999, 
                                 cpu_threads = 1)

table(sc_lisa$cluster) 

hex_spe <- scider::findNbrsSpatial(hex_spe, radius = 250, dist_func = "exp", standardisation = "none")
sc_lisa <- scider::localMoran(hex_spe, x, y, at = "cell", permutations = 999, 
                                 cpu_threads = 1)

table(sc_lisa$cluster) 

```


# counts from scider

scider binning and aggreted counts
```{r}
ct_group = "cell_type"
ct1 <- spe@colData[[ct_group]]
coi <- as.character(unique(ct1)) # needs to be not factor level
spe_hex_cell <- scider::gridDensity(spe, coi = coi, grid.type = "hex",grid.length.x = 50, id = ct_group)
spe_hex <- scider::gridSPE(spe_hex_cell, cell.count = TRUE, id = ct_group)

scider_counts <- spe_hex@assays@data$counts
dim(scider_counts)
```

manually aggregate counts
```{r}
sf_hex <- sf::st_as_sfc(grid2sf(spe_hex_cell))
sf_hex <- sf::st_as_sf(sf_hex)

xy_allcells <- sf::st_as_sf(as.data.frame(SpatialExperiment::spatialCoords(spe_hex_cell)),coords = c("x_centroid", "y_centroid"))
overlap_ind <- sf::st_intersects(xy_allcells, sf_hex, sparse = TRUE)

n_cells <- length(overlap_ind)
n_bins  <- nrow(sf_hex)

i <- rep(seq_len(n_cells), lengths(overlap_ind))
j <- unlist(overlap_ind)

H <- Matrix::sparseMatrix(
  i = i,
  j = j,
  x = 1,
  dims = c(n_cells, n_bins)
)

table(Matrix::rowSums(H))   # mostly 1
Matrix::colSums(H)[1:5]     # cells per bin

manual_counts <- counts_mat %*% H
dim(manual_counts)
```


compare
```{r}
diff_mat <- manual_counts - scider_counts
diff_df <- as.data.frame(as.matrix(diff_mat))
diff_df$gene <- rownames(diff_df)
dim(diff_df)
table(diff_df != 0)

library(tidyr)
library(dplyr)
nonzero_diff <- diff_df %>%
  pivot_longer(
    cols = -gene,
    names_to = "bin",
    values_to = "diff"
  ) %>%
  filter(diff != 0)

nonzero_diff

unique(nonzero_diff$bin)
unique(nonzero_diff$gene)
```


```{r}
bin_idx <- 18731
hex_sel <- sf_hex[c(bin_idx), ]

cell2bin_sel <- sf::st_intersects(xy_allcells, hex_sel, sparse = TRUE)
cell_idx <- which(lengths(cell2bin_sel) > 0)

cells_sel <- xy_allcells[cell_idx, ]
cells_sel

ggplot() +
  geom_sf(data = sf_hex, fill = NA, color = "grey80", linewidth = 0.1) +
  geom_sf(data = hex_sel, color = "black", linewidth = 0.4, alpha = 0.6) +
  geom_sf(data = cells_sel, size = 0.25, alpha = 0.8, color="red") +
  coord_sf(expand = FALSE) +
  theme_void() +
  theme(legend.position = "bottom")

sum(counts_mat["ACTG2", cell_idx])
manual_counts["ACTG2", bin_idx]
scider_counts["ACTG2", bin_idx]
```

```{r}
bin_idx <- 18882
hex_sel <- sf_hex[c(bin_idx), ]

cell2bin_sel <- sf::st_intersects(xy_allcells, hex_sel, sparse = TRUE)
cell_idx <- which(lengths(cell2bin_sel) > 0)

cells_sel <- xy_allcells[cell_idx, ]
cells_sel

ggplot() +
  geom_sf(data = sf_hex, fill = NA, color = "grey80", linewidth = 0.1) +
  geom_sf(data = hex_sel, color = "black", linewidth = 0.4, alpha = 0.6) +
  geom_sf(data = cells_sel, size = 0.25, alpha = 0.8, color="red") +
  coord_sf(expand = FALSE) +
  theme_void() +
  theme(legend.position = "bottom")

sum(counts_mat["ACTG2", cell_idx])
manual_counts["ACTG2", bin_idx]
scider_counts["ACTG2", bin_idx]
```
```{r}
bin_idx<- c(18731, 18882)
hex_sel <- sf_hex[bin_idx, ]

cell2bin_sel <- sf::st_intersects(xy_allcells, hex_sel, sparse = TRUE)
cell_idx <- which(lengths(cell2bin_sel) > 0)

cells_sel <- xy_allcells[cell_idx, ]
cells_sel

ggplot()+
  geom_sf(data = hex_sel, color = "black", linewidth = 0.4, alpha = 0.6) +
  geom_sf(data = cells_sel, size = 0.5, alpha = 0.8, color="red") +
  coord_sf(expand = FALSE) +
  theme_void() +
  theme(legend.position = "bottom")
```

# test spdep for all LR

```{r}
library(CellChat)

# NOTE: use ligand/receptor.symbol as gene name, ligand/receptor columns are bilogical entity names which may not be a gene, e.g. RA-ALDH1A3

filter_genes <- function(gene_column, gene_list) { # function to filter out the whole interaction if missing any L/R subunits
  sapply(strsplit(as.character(gene_column), ", "), function(genes) {
    filtered_genes <- genes[genes %in% gene_list]
    if (length(filtered_genes) != length(genes)) {
      return(NA)
    } else {
      return(paste(filtered_genes, collapse = ", "))
    }
  })
}


getLRpairs <- function(gene_panel, LR_df = CellChatDB.human$interaction){
  
  LR_df$ligand.symbol <- filter_genes(LR_df$ligand.symbol, gene_panel)
  LR_df$receptor.symbol <- filter_genes(LR_df$receptor.symbol, gene_panel)
  
  LR_included <- LR_df[!(is.na(LR_df$ligand.symbol) | is.na(LR_df$receptor.symbol)), ]
  
  return(LR_included)
}

filterLRpairs <- function(counts, min_ligand = 10, min_receptor = 10, LR_df = CellChatDB.human$interaction) {
  #counts = spe@assays@data$counts
  
  filtered_counts_ligand <- counts[rowSums(counts >= min_ligand) > 0, ] # at least one spot has more than min_ligand counts
  filtered_counts_receptor <- counts[rowSums(counts >= min_receptor) > 0, ]
  
  LR_filtered_ligand <- getLRpairs(gene_panel = rownames(filtered_counts_ligand), LR_df)
  LR_filtered_receptor <- getLRpairs(gene_panel = rownames(filtered_counts_receptor), LR_df)
  
  intersect_LR <- intersect(rownames(LR_filtered_ligand), rownames(LR_filtered_receptor))
  
  LR_filtered <- LR_filtered_ligand[intersect_LR,]
  
  return(LR_filtered)
  
}

LR_pairs_filtered <- filterLRpairs(counts = hex_gene_counts, min_ligand = 10, min_receptor = 10, LR_df = CellChatDB.human$interaction)

LR_pairs_filtered

rownames(hex_gene_counts)


unique(LR_pairs_filtered$annotation)
```

```{r}
## ---------------------------
## Helper: parse multi-unit gene strings and take per-bin MIN
## ---------------------------
parse_units <- function(s) {
  s <- as.character(s)
  s <- gsub("\\s+", "", s)
  # allow "A,B" or "A_B" or "A, B"
  unlist(strsplit(s, "[,_]"))
}

# return numeric vector length n_hex
get_min_expr <- function(gene_str, hex_gene_counts) {
  genes <- parse_units(gene_str)
  genes <- genes[genes %in% rownames(hex_gene_counts)]
  if (length(genes) == 0) {
    return(rep(0, n_hex))  # gene(s) absent -> 0
  }
  if (length(genes) == 1) {
    return(as.numeric(hex_gene_counts[genes, ]))
  }
  # per-bin minimum across subunits
  mat <- hex_gene_counts[genes, , drop = FALSE]
  apply(mat, 2, min)
}
  
# test
gene_str <- "CXCL12, CXCR4"
parse_units("CXCL12, CXCR4")
mat <- hex_gene_counts[c("CXCL12", "CXCR4"), , drop = FALSE]
t <- apply(mat, 2, min)
as.matrix(mat)[, 192:200]
t[192:200]
```
```{r}
LR_df_add_mode <- function(LR_df, col = "annotation", default_mode = "diffuse", 
                           diffuse_category = c("Secreted Signaling", "Non-protein Signaling")) {
  # Case 1: annotation column missing → all diffuse
  if (!col %in% colnames(LR_df)) {
    LR_df$ccc_mode <- default_mode
    message(paste0(col, " column is missing. Setting ccc_mode as '", default_mode, "' for all."))
    
    return(LR_df)
  }
  
  # Case 2: annotation exists
  LR_df$ccc_mode <- 
    ifelse(
      LR_df[[col]] %in% diffuse_category,
      "diffuse",
      "nearby"
  )
  message(paste0("ccc_mode is 'diffuse' for category: ", paste0(diffuse_category, collapse = ", "), "; 'nearby' for others."))
  
  LR_df
}

LR_pairs_filtered <- LR_df_add_mode(LR_pairs_filtered)

LR_pairs_filtered[, c("annotation", "ccc_mode")]
```

```{r}
hex_binning_cells <- function(
    coords_df = NULL,
    counts_matrix = NULL,
    spe = NULL,
    hex_size = 50) {
  
  ## ---------------------------
  ## 0. Input handling
  ## ---------------------------
  if (!is.null(spe)) {
    coords_df <- as.data.frame(spe@int_colData$spatialCoords)
    counts_matrix <- spe@assays@data$counts
  } else {
    stopifnot(!is.null(coords_df), !is.null(counts_matrix))
    stopifnot(inherits(counts_matrix, c("matrix", "dgCMatrix")))
  }
  
  coords_df$cell_id <- rownames(coords_df)
  
  required_cols <- c("cell_id", "x_centroid", "y_centroid")
  stopifnot(all(required_cols %in% colnames(coords_df)))
  
  stopifnot(all(colnames(counts_matrix) %in% coords_df$cell_id))

  ## ---------------------------
  ## 1. sf cells
  ## ---------------------------
  cell_sf <- sf::st_as_sf(
    coords_df,
    coords = c("x_centroid", "y_centroid"),
    crs = NA
  )
  
  ## ---------------------------
  ## 2. Hex binning
  ## ---------------------------
  # create bins
  hex_geom <- sf::st_make_grid( # only polygon info
    cell_sf,
    cellsize = hex_size,
    what = "polygons",
    square = FALSE
  )
  
  hex_sf <- sf::st_sf( # sf object
    hex_id = seq_along(hex_geom),
    geometry = hex_geom
  )
  dim(hex_sf)
  
  # map cells to bins
  cell_hex_sf <- sf::st_join(cell_sf, hex_sf, join = sf::st_intersects)
  cell_hex_df <- sf::st_drop_geometry(cell_hex_sf)
  dim(cell_hex_df)
  length(unique(cell_hex_df$hex_id))
  
  ## ---------------------------
  ## 3. Aggregate counts
  ## ---------------------------
  cell_to_hex <- cell_hex_df$hex_id
  names(cell_to_hex) <- cell_hex_df$cell_id
  cell_to_hex <- cell_to_hex[colnames(counts_matrix)]
  
  n_hex <- nrow(hex_sf) # hex_sf contains ALL hexes including empty bins
  hex_factor <- factor(cell_to_hex, levels = seq_len(n_hex))
  
  H <- Matrix::sparse.model.matrix(~ hex_factor - 1)
  hex_gene_counts <- counts_matrix %*% H
  dim(hex_gene_counts)
  
  hex_sf$n_cells <- as.numeric(Matrix::colSums(H))
  dim(hex_sf)
  
  list(
    hex_sf = hex_sf,
    hex_gene_counts = hex_gene_counts
  )

}

# test
binning_res <- hex_binning_cells(coords_df, counts_matrix)
binning_res <- hex_binning_cells(coords_df, as.matrix(counts_matrix))

hex_sf <- binning_res$hex_sf
hex_gene_counts <- binning_res$hex_gene_counts
```


```{r}
coords_df <- as.data.frame(spe@int_colData$spatialCoords)
counts_matrix <- spe@assays@data$counts

runBLISA <- function(
  coords_df = NULL,
  counts_matrix = NULL,
  LR_df = NULL,
  spe = NULL,
  hex_size = 50,
  dmax = 250,
  nsim = 999,
  p_cutoff = 0.05,
  default_mode = "diffuse"
) {
  
  ## ---------------------------
  ## Hex binning
  ## ---------------------------
  binning_res <- hex_binning_cells(coords_df, counts_matrix, spe, hex_size)

  ## ---------------------------
  ## Spatial weights
  ## ---------------------------
  centroids <- sf::st_centroid(hex_sf)
  coords <- sf::st_coordinates(centroids)
  
  # exponential distance weight
  dist_nb <- spdep::dnearneigh(coords, 0, dmax)
  
  weight_at_dmax <- 0.01 # exp dist weight=0.01 for dist=dmax
  dist_wt <- spdep::nb2listwdist(
    dist_nb,
    hex_sf,
    type = "exp",
    style = "W",
    alpha = -log(weight_at_dmax) / dmax 
  )
  
  # queen weight order = 1
  queen_nb <- dnearneigh(centroids, 0, 1.2*hex_size)
  queen_wt <- spdep::nb2listwdist(queen_nb, centroids, type="idw", style="W", zero.policy = TRUE)

  ## ---------------------------
  ## Local bivariate Moran for all LR pairs
  ## ---------------------------
  LR_out <- LR_df_add_mode(LR_df)

  LR_out$sig_numbers <- integer(nrow(LR_out))
  LR_out$sig_index   <- vector("list", nrow(LR_out))
  LR_out$sig_pval    <- vector("list", nrow(LR_out))
  LR_out$all_pval    <- vector("list", nrow(LR_out))
  LR_out$all_lisa    <- vector("list", nrow(LR_out))
  LR_out$ccc_mode    <- character(nrow(LR_out))
  
  for (i in seq_len(nrow(LR_df))) {
    message(rownames(LR_df)[i])
    
    ligand   <- LR_df$ligand.symbol[i]
    receptor <- LR_df$receptor.symbol[i]

    mode <- LR_pairs_filtered$ccc_mode[i]
    wt <- if (mode == "nearby") queen_wt else dist_wt
    message("ccc mode is ", mode)
    
    # bivariate vectors per hex (min for multi-unit)
    x <- get_min_expr(receptor, hex_gene_counts)  # receptor
    y <- get_min_expr(ligand, hex_gene_counts)    # ligand

    # spdep::localmoran_bv cannot include isolates -> subset and map back
    # cards <- spdep::card(wt$neighbours)
    # keep_hex <- cards > 0
    # 
    # wt_keep <- spdep::subset.listw(wt, subset = keep_hex, zero.policy = TRUE)
    # res_keep <- spdep::localmoran_bv(x[keep_hex], y[keep_hex], wt_keep, nsim = nsim)
    # 
    # res_bv <- matrix(NA_real_, nrow = n_hex, ncol = ncol(res_keep))
    # colnames(res_bv) <- colnames(res_keep)
    # res_bv[keep_hex, ] <- res_keep
    
    # bivariate local moran
    res_bv <- spdep::localmoran_bv(x, y, wt, nsim = nsim)
    
    hs <- hotspot(
      res_bv,
      Prname = "Pr(folded) Sim",
      cutoff = p_cutoff,
      quadrant.type = "pysal",
      p.adjust = "none"
    )

    idx <- (hs == "High-High")
    idx[is.na(idx)] <- FALSE

    HH_idx  <- which(idx)
    HH_pval <- res_bv[idx, "Pr(folded) Sim"]

    # write back into LR_out
    LR_out$sig_numbers[i] <- length(HH_idx)
    LR_out$sig_index[[i]] <- HH_idx
    LR_out$sig_pval[[i]]  <- HH_pval
    LR_out$all_pval[[i]]  <- res_bv[, "Pr(folded) Sim"]
    LR_out$all_lisa[[i]]  <- res_bv[, "Ibvi"]
    LR_out$ccc_mode[i]    <- mode
  }

  LR_out <- LR_out[order(-LR_out$sig_numbers), , drop = FALSE]
  
  ## ---------------------------
  ## Return both results + binned data
  ## ---------------------------
  front_cols <- c("ccc_mode", "sig_numbers", "sig_index", "sig_pval")

  LR_out <- LR_out[, c(front_cols, setdiff(colnames(LR_out), front_cols))]

  list(
    LR_out = LR_out,
    hex_sf = hex_sf,
    hex_gene_counts = hex_gene_counts
  )
  
}

```

```{r}
coords_df <- as.data.frame(spe@int_colData$spatialCoords)
counts_matrix <- spe@assays@data$counts

LR_pairs_filtered <- filterLRpairs(counts = hex_gene_counts, 
                                   min_ligand = 10, min_receptor = 10, 
                                   LR_df = CellChatDB.human$interaction)

system.time(BLISAres <- runBLISA(coords_df, counts_matrix, LR_pairs_filtered))
```


```{r}
LR_sum <- BLISAres$LR_out
LR_sum[, 1:7]
```

